apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: fluidos  # usa il namespace corretto
spec:
  selector:
    app: orchestrator  # deve combaciare con la label del tuo deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

