apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: liqoconfiguration-cluster-role
  namespace: fluidos
rules:
- apiGroups: ["networking.liqo.io"]
  resources: ["configurations"]
  verbs: ["get", "list", "watch"]