apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-border-controller
  namespace: fluidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-border-controller
  template:
    metadata:
      labels:
        app: secure-border-controller
    spec:
      serviceAccountName: secure-border-controller
      containers:
      - name: secure-border-controller
        image: secure-border-controller
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
