apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-network-intent
  namespace: fluidos
data:
  name: "example-intent"
  isCNF: "true"
  priority: "3000"
  action: Allow
  acceptMonitoring: "true"
  networkIntents: |
    [
    {
      "source": {
        "resourceSelector": {
          "isHostCluster": false,
          "typeIdentifier": "PodNamespaceSelector",
          "selector": {
            "pod": {
              "app": "app-payment-1"
            },
            "namespace": {
              "name": "payments"
            }
          }
        }
      },
      "destination": {
        "resourceSelector": {
          "isHostCluster": true,
          "typeIdentifier": "PodNamespaceSelector",
          "selector": {
            "pod": {
              "*": "*"
            },
            "namespace": {
              "*": "*"
            }
          }
        }
      },
      "destinationPort": "80",
      "protocolType": "TCP"
    },
    {
      "source": {
        "resourceSelector": {
          "isHostCluster": false,
          "typeIdentifier": "PodNamespaceSelector",
          "selector": {
            "pod": {
              "app": "app-payment-2"
            },
            "namespace": {
              "name": "payments"
            }
          }
        }
      },
      "destination": {
        "resourceSelector": {
          "isHostCluster": true,
          "typeIdentifier": "PodNamespaceSelector",
          "selector": {
            "pod": {
              "*": "*"
            },
            "namespace": {
              "*": "*"
            }
          }
        }
      },
      "destinationPort": "90",
      "protocolType": "TCP"
    },
    {
      "source": {
        "resourceSelector": {
          "isHostCluster": false,
          "typeIdentifier": "PodNamespaceSelector",
          "selector": {
            "pod": {
              "app": "mobile-products"
            },
            "namespace": {
              "name": "products"
            }
          }
        }
      },
      "destination": {
        "resourceSelector": {
          "isHostCluster": true,
          "typeIdentifier": "CIDRSelector",
          "selector": "142.250.0.0/15"
        }
      },
      "destinationPort": "*",
      "protocolType": "ALL"
    },
    {
      "source": {
        "resourceSelector": {
          "isHostCluster": false,
          "typeIdentifier": "PodNamespaceSelector",
          "selector": {
            "pod": {
              "app": "desktop-products"
            },
            "namespace": {
              "name": "products"
            }
          }
        }
      },
      "destination": {
        "resourceSelector": {
          "isHostCluster": true,
          "typeIdentifier": "PodNamespaceSelector",
          "selector": {
            "pod": {
              "*": "*"
            },
            "namespace": {
              "*": "*"
            }
          }
        }
      },
      "destinationPort": "85",
      "protocolType": "UDP"
    }
    ]
